CREATE TABLE IF NOT EXISTS groups (
id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
name TEXT NOT NULL UNIQUE);

CREATE TABLE IF NOT EXISTS users (
id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
login TEXT NOT NULL UNIQUE,
password TEXT NOT NULL,
groupId INTEGER NOT NULL,
FOREIGN KEY (groupId)
REFERENCES groups (id)
ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS roles (
id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
description TEXT NOT NULL UNIQUE);

CREATE TABLE IF NOT EXISTS groupsAndRoles (
groupId INTEGER NOT NULL,
roleId INTEGER NOT NULL,
PRIMARY KEY (groupId, roleId),
FOREIGN KEY (groupId)
REFERENCES groups (id)
ON DELETE CASCADE,
FOREIGN KEY (roleId)
REFERENCES roles (id)
ON DELETE CASCADE
);