PRAGMA foreign_keys = ON;

CREATE TABLE IF NOT EXISTS groups(
id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
group_name TEXT NOT NULL);

CREATE TABLE IF NOT EXISTS users(
    id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    login TEXT NOT NULL,
    password TEXT NOT NULL,
    registration_date DATE NOT NULL,
    group_id INTTEGER,
    FOREIGN KEY (group_id)
    REFERENCES groups (id)
    ON DELETE CASCADE);

CREATE TABLE IF NOT EXISTS topics(
    id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    topic_title TEXT NOT NULL,
    date_created DATE NOT NULL,
    author_id INTEGER,
    FOREIGN KEY (author_id)
    REFERENCES users (id)
    ON DELETE CASCADE);

CREATE TABLE IF NOT EXISTS posts(
    id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    content TEXT NOT NULL,
    date_created DATE NOT NULL,
    author_id INTEGER,
    topic_id INTEGER,
    FOREIGN KEY (author_id)
    REFERENCES users (id)
    ON DELETE CASCADE,
    FOREIGN KEY (topic_id)
    REFERENCES topics (id)
    ON DELETE CASCADE);

CREATE TABLE IF NOT EXISTS votes(
    id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    up_votes INTEGER DEFAULT 0,
    down_votes INTEGER DEFAULT 0,
    post_id INTEGER,
    FOREIGN KEY (post_id)
    REFERENCES posts (id)
    ON DELETE CASCADE);